version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: blog