name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Setup Maven wrapper
        run: |
          if [ ! -f .mvn/wrapper/maven-wrapper.jar ]; then
            mvn wrapper:wrapper
          fi
    
      - name: Set executable permissions for Maven wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B -DskipTests package

      - name: Run tests
        run: ./mvnw -B test

      - name: Lint Terraform formatting (dry-run)
        if: ${{ always() }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - run: |
          cd infra
          terraform fmt -check -recursive
        continue-on-error: true


